spring.application.name=trip-advisor

# upstream service properties
# planning services
accommodation.service.url=http://localhost:7070/trip-planning/accommodations/
event.service.url=http://localhost:7070/trip-planning/events/
local-recommendation.service.url=http://localhost:7070/trip-planning/local-recommendations/
transportation.service.url=http://localhost:7070/trip-planning/transportation/
weather.service.url=http://localhost:7070/trip-planning/weather/

# search and reservation services
flight-search.service.url=http://localhost:7070/flight/search/
flight-reservation.service.url=http://localhost:7070/flight/reserve/

# virtual thread enabled/disabled
spring.threads.virtual.enabled=true
