FROM bellsoft/liberica-openjdk-alpine:25
WORKDIR app
ADD https://github.com/Mick-J/trip-advisor/tree/main/external-service/external-services.jar external-services.jar
CMD java -jar external-services.jar